site_name: OUTBREAK
site_url: https://outbreak-mc.github.io/

extra_css:
  - "stylesheets/extra.css"
  - "stylesheets/index.css"
  - "stylesheets/stars.css"

theme:
  logo: assets/images/logo.png
  icon: assets/images/logo.png
  favicon: assets/images/logo.png
  name: material
  language: ru
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    # - toc.integrate
    - navigation.table
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    primary: custom
    scheme: slate

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/outbreak-mc
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/fhgkRff
    - icon: fontawesome/brands/vk 
      link: https://vk.com/outbreak_mc

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons

nav:
  - –ì–ª–∞–≤–Ω–∞—è: http://localhost:5173/

  # - SKYHIGH EVENT: 
  #   - skyhigh/index.md

  - Quality-of-Life —Å–±–æ—Ä–∫–∞:
    - modpack/index.md
    - –û–±–∑–æ—Ä QoL-—Å–±–æ—Ä–∫–∏ OUTBREAK: modpack/review.md
    - –£—Å—Ç–∞–Ω–æ–≤–∫–∞ —Å–±–æ—Ä–æ–∫: modpack/installation.md
    - –£—Å—Ç–∞–Ω–æ–≤–∫–∞ Java: modpack/java-installation.md
    - –ü—Ä–æ–±–ª–µ–º—ã –∏ –≤–æ–ø—Ä–æ—Å—ã: modpack/installation-issues.md

  # - üéÑ MODBREAK-2024:
  #   - MODBREAK-2024: modbreak2024/index.md

  - –ü—Ä–∞–≤–∏–ª–∞ –ø—Ä–æ–µ–∫—Ç–∞:
    - –û—Å–Ω–æ–≤–Ω–æ–µ –ø–æ–ª–æ–∂–µ–Ω–∏–µ –ø—Ä–æ–µ–∫—Ç–∞: rules/index.md
    - –ü—Ä–∏–º–µ—á–∞–Ω–∏—è –æ —Ä–∞–±–æ—Ç–µ –ø–µ—Ä—Å–æ–Ω–∞–ª–∞: rules/staff.md
